name: quickquotes
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:

  share_plus: ^7.2.1
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  provider: ^6.1.1

  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/images/bg_drawer.png
    - assets/images/einstein.jpg
    - assets/images/franklin.jpg
    - assets/images/obama.jpg
    - assets/images/ayn_rand.jpg
    - assets/images/anne_frank.jpg

  uses-material-design: true


